from pathlib import Path

YEARS = list(range(2013, 2026))

TARGET_TOKENS_PER_YEAR = 1_000_000_000
LANGUAGE_SCORE_THRESHOLD = 0.65

EMBEDDING_DIM = 300
WINDOW_SIZE = 5
NUM_NEGATIVE_SAMPLES = 5
MIN_WORD_FREQ = 50
MAX_VOCAB_SIZE = 200_000
LEARNING_RATE = 0.05
BATCH_SIZE = 16384
NUM_EPOCHS = 3
SUBSAMPLING_THRESHOLD = 1e-4
SEED = 42

MIN_YEARS_FOR_VOCAB = 12

DATA_DIR = Path("data")
TOKENS_DIR = DATA_DIR / "tokens"
VOCAB_DIR = DATA_DIR / "vocab"
MODELS_DIR = Path("models")
EMBEDDINGS_DIR = MODELS_DIR / "embeddings"
ALIGNED_DIR = MODELS_DIR / "aligned"
DRIFT_DIR = MODELS_DIR / "drift"
